#!/usr/bin/env python3
"""Translate 207 missing i18n keys into ES/PT/DE/FR/HI and merge into each /public/locales/{lang}.json.

Each existing locale file has 637 keys. We add 207 new keys (total 844) sorted alphabetically
to match the existing structure.
"""
import json
from pathlib import Path

LOCALES_DIR = Path("/home/z/my-project/public/locales")

# ----- 207 translations per language -----
# Each dict maps key -> translated value. Order follows the EN dictionary logical grouping
# but the final JSON is sorted alphabetically by key.

TRANSLATIONS = {
    "es": {
        # ---- bowel_* (74 keys) ----
        "bowel_tracker": "Baño",
        "bowel_went": "Fui al baño",
        "bowel_went_short": "Fui",
        "bowel_today": "visitas hoy",
        "bowel_history": "Historial (7 días)",
        "bowel_no_records": "Aún nada. ¡Marca cuando vayas!",
        "bowel_last_time": "Última visita",
        "bowel_hours_ago": "h atrás",
        "bowel_time_since": "Tiempo desde la última",
        "bowel_warning_title": "¡Atención! 🚨",
        "bowel_warning_subtitle": "Ya pasaron {h}h desde tu última visita. ¡Hora de ir!",
        "bowel_correlation": "Correlación con la comida",
        "bowel_avg_after": "Promedio de horas después",
        "bowel_times_logged": "veces registrado",
        "bowel_no_correlation": "Agrega comida y marca visitas para ver patrones",
        "bowel_consistency": "Consistencia",
        "bowel_normal": "Normal",
        "bowel_loose": "Suave",
        "bowel_hard": "Dura",
        "bowel_bristol_type": "Tipo",
        "bowel_bristol_scale": "Escala de Bristol",
        "bowel_bristol_1": "Nueces",
        "bowel_bristol_2": "Salchicha con grumos",
        "bowel_bristol_3": "Salchicha con grietas",
        "bowel_bristol_4": "Salchicha suave",
        "bowel_bristol_5": "Bolitas suaves",
        "bowel_bristol_6": "Piezas esponjosas",
        "bowel_bristol_7": "Acuoso",
        "bowel_bristol_1_desc": "Grumos duros, difíciles de pasar (estreñimiento)",
        "bowel_bristol_2_desc": "Con grumos, dura (estreñimiento)",
        "bowel_bristol_3_desc": "Superficie con grietas (normal)",
        "bowel_bristol_4_desc": "Suave, lisa (ideal)",
        "bowel_bristol_5_desc": "Suave con bordes definidos (poca fibra)",
        "bowel_bristol_6_desc": "Rasgada, blanda (diarrea leve)",
        "bowel_bristol_7_desc": "Líquida, sin piezas sólidas (diarrea)",
        "bowel_symptoms": "Síntomas / notas",
        "bowel_symptoms_placeholder": "Hinchazón, dolor, náuseas...",
        "bowel_symptoms_bloating": "Hinchazón",
        "bowel_symptoms_pain": "Dolor",
        "bowel_symptoms_nausea": "Náuseas",
        "bowel_symptoms_heartburn": "Acidez",
        "bowel_symptoms_cramps": "Calambres",
        "bowel_symptoms_none": "Sin síntomas",
        "bowel_tracking_hint": "💡 Para insights útiles, registra lo que comes y cuándo vas al baño",
        "bowel_warning_1": "¡Depósito madurando, retiro pronto! 💰",
        "bowel_warning_2": "¡No eres camello, no puedes acumular! 🐪",
        "bowel_warning_3": "¡Cuidado, la presión sube! 💥",
        "bowel_warning_4": "¡Capacidad de almacenamiento superada! ⚠️",
        "bowel_warning_5": "Tu intestino pregunta: ¿cuándo? 🤔",
        "bowel_warning_6": "¡Bomba de tiempo! 💣",
        "bowel_warning_7": "¡Fuegos artificiales en camino! 🎆",
        "bowel_warning_8": "¡No vayas a una cita! 💔",
        "bowel_warning_9": "¡Almacén lleno, descarga! 📦",
        "bowel_warning_10": "¡No lo retengas — es malo! 🚫",
        "bowel_warning_11": "¡Hora de entregar la mercancía! 🏭",
        "bowel_warning_12": "¡Tu intestino espera tu visita! 🚪",
        "bowel_morning_title": "¿Ya fuiste hoy? 🚽",
        "bowel_morning_1": "Una vez al día es la norma, ¡sin excepciones! 📅",
        "bowel_morning_2": "¿Dónde están los resultados? ¡Entrega la mercancía! 📦",
        "bowel_morning_3": "No puedes acumular, ¡hay que compartir! 🤲",
        "bowel_morning_4": "Producción detenida — ¡desbloquea la cinta! ⚙️",
        "bowel_morning_5": "¡Tu intestino espera tu visita! 🚪",
        "bowel_morning_dismiss": "¡Ya fui!",
        "bowel_morning_later": "Luego",
        "bowel_disable": "Desactivar seguimiento",
        "bowel_enable": "Activar seguimiento",
        "bowel_disabled_hint": "Seguimiento desactivado. Actívalo en ajustes.",
        "bowel_xp_gain": "¡+5 XP por registrar!",
        "bowel_xp_capped": "XP al máximo hoy (máx 3)",
        "bowel_edit": "Editar",
        "bowel_edit_time": "Hora",
        "bowel_edit_date": "Fecha",
        "bowel_save": "Guardar",
        "bowel_cancel": "Cancelar",
        # ---- digest_* (44 keys) ----
        "digest_section": "Tu resumen",
        "digest_period": "últimos 7 días",
        "digest_avg_rhythm": "Ritmo promedio",
        "digest_avg_rhythm_unit": "visitas/día",
        "digest_avg_rhythm_desc": "Cuántas veces al día vas.",
        "digest_top_type": "Tipo más común",
        "digest_top_type_unit": "de todas las visitas",
        "digest_top_type_desc_normal": "¡Normal — todo bien!",
        "digest_top_type_desc_constipation": "Más cerca del estreñimiento. Bebe más agua.",
        "digest_top_type_desc_diarrhea": "Más cerca de la diarrea. Revisa tu dieta.",
        "digest_food_trigger": "Desencadenante",
        "digest_food_trigger_unit": "síntomas después",
        "digest_food_trigger_desc": "Esta comida causa más síntomas.",
        "digest_best_day": "Mejor día",
        "digest_best_day_unit": "sin síntomas",
        "digest_best_day_unit_with": "{n} síntomas",
        "digest_best_day_desc": "Tu intestino funcionó más suave este día.",
        "digest_progress": "Progreso",
        "digest_progress_unit_one": "día registrado",
        "digest_progress_unit_few": "días registrados",
        "digest_progress_unit_many": "días registrados",
        "digest_progress_desc": "Suficiente para ver patrones.",
        "digest_no_data": "No hay suficientes datos. ¡Registra visitas y comida!",
        "digest_insight_title": "Insight del día",
        "digest_insight_1": "Parece que a tu intestino le gusta la rutina.",
        "digest_insight_2": "La comida pesada rara vez pasa desapercibida.",
        "digest_insight_3": "El Tipo 5 volvió a liderar.",
        "digest_insight_4": "Menos agua — el sistema trabajó más duro.",
        "digest_insight_5": "Después de una cena tardía, todo se pone más interesante.",
        "digest_insight_6": "A tu intestino no le gustan las sorpresas.",
        "digest_insight_7": "La estabilidad es tu mejor patrón.",
        "digest_insight_8": "Los lácteos podrían no ser tus amigos aquí.",
        "digest_insight_9": "Después de comida grasosa, el panorama es más ruidoso.",
        "digest_insight_10": "Tu cuerpo envía señales — y no en silencio.",
        "digest_insight_11": "Tienes tus propios desencadenantes.",
        "digest_insight_12": "El Tipo 5 aparece más de lo que querrías.",
        "digest_insight_13": "Cuando la rutina se rompe, los datos también se vuelven caóticos.",
        "digest_insight_14": "A tu intestino le gusta la comida simple y clara.",
        "digest_insight_15": "Un snack nocturno rara vez queda sin respuesta.",
        "digest_insight_16": "Algunos días todo funciona más suave.",
        "digest_insight_17": "Hay un patrón vivo aquí.",
        "digest_insight_18": "Comida y síntomas están más conectados de lo que parece.",
        "digest_insight_19": "Tu intestino parece bastante hablador.",
        "digest_insight_20": "No adivinamos — ya tenemos pistas.",
        # ---- report_* (34 keys) ----
        "report_section": "Informe para el médico",
        "report_desc": "Exportar PDF/CSV para gastroenterólogo",
        "report_button": "📄 Informe para el médico",
        "report_csv_button": "📊 Descargar CSV",
        "report_title": "Informe del diario intestinal",
        "report_subtitle": "para gastroenterólogo",
        "report_period": "Periodo",
        "report_period_7": "7 días",
        "report_period_30": "30 días",
        "report_period_90": "90 días",
        "report_print": "🖨️ Imprimir / Guardar PDF",
        "report_summary": "Resumen",
        "report_patient": "Paciente",
        "report_date_range": "Periodo de observación",
        "report_days_tracked": "días registrados",
        "report_avg_farts": "Pedos/día",
        "report_avg_poops": "Deposiciones/día",
        "report_norm": "norma",
        "report_water_avg": "Agua (vasos/día)",
        "report_walks_week": "Paseos por semana",
        "report_bristol_distribution": "Escala de Bristol (distribución)",
        "report_food_triggers": "Top desencadenantes",
        "report_food_trigger_farts": "pedos después",
        "report_food_trigger_poops": "horas hasta deposición",
        "report_30day_chart": "Tendencia del periodo",
        "report_symptoms_log": "Registro de síntomas",
        "report_no_symptoms": "Sin síntomas registrados",
        "report_no_data": "Datos insuficientes para el periodo seleccionado",
        "report_generated": "Informe generado",
        "report_signature": "Generado por la app Contador de Pedos",
        "report_disclaimer": "Solo informativo. No sustituye la consulta médica.",
        "report_farts_chart_label": "pedos",
        "report_poops_chart_label": "deposiciones",
        "report_track_food_hint": "💡 Consejo: registra comida para correlacionar con pedos y deposiciones",
        # ---- health_tip_* (21 keys) ----
        "health_tip_title": "Consejo del día",
        "health_tip_1": "🚶 Caminar 15 min después de comer mejora la digestión y reduce los gases.",
        "health_tip_2": "💧 Bebe 6-8 vasos de agua al día — ablandan las heces y previenen el estreñimiento.",
        "health_tip_3": "🚽 Ir al baño una vez al día es normal. ¡No lo retengas!",
        "health_tip_4": "🥦 La fibra (verduras, frutas, cereales integrales) es la mejor amiga de tu intestino.",
        "health_tip_5": "⏰ Un horario regular (mañana tras el desayuno) entrena tu intestino.",
        "health_tip_6": "🏃 Movimiento = peristaltismo. Vida sedentaria = estreñimiento.",
        "health_tip_7": "☕ El café de mañana estimula el peristaltismo — pero no más de 2-3 tazas.",
        "health_tip_8": "🥛 ¿Los lácteos te dan gases? Quizás seas intolerante a la lactosa.",
        "health_tip_9": "🌙 No comas 3 horas antes de dormir — pedos nocturnos y hinchazón garantizados.",
        "health_tip_10": "🧘 El estrés afecta tu intestino directo. Relájate — y tu intestino lo agradecerá.",
        "health_tip_11": "💩 Normal: 1-2 veces al día, Tipo 4 (salchicha suave) en la escala de Bristol.",
        "health_tip_12": "🫘 Frijoles, repollo, brócoli — gases garantizados, ¡pero es saludable!",
        "health_tip_13": "🍞 El pan blanco y la comida rápida lentifican la digestión. Elige integral.",
        "health_tip_14": "🚭 Fumar altera el peristaltismo y la microbiota intestinal.",
        "health_tip_15": "💊 Los antibióticos matan la flora benéfica. Restáurala con probióticos.",
        "health_tip_16": "🍎 Manzanas con cáscara — fuente natural de pectina para tu intestino.",
        "health_tip_17": "🍌 Los plátanos ayudan con la diarrea leve — reponen potasio.",
        "health_tip_18": "🍵 El té de menta alivia calambres e hinchazón tras comer.",
        "health_tip_19": "🥗 Una ensalada antes del plato principal prepara el estómago y reduce gases.",
        "health_tip_20": "🚶‍♂️ 10000 pasos al día = intestino sano. ¡Comprobado!",
        # ---- walk_* (18 keys) ----
        "walk_tracker": "Caminar",
        "walk_went": "Caminé 🚶",
        "walk_went_short": "Caminé",
        "walk_today": "paseos hoy",
        "walk_history": "Historial (7 días)",
        "walk_minutes": "minutos",
        "walk_no_records": "Aún nada. ¡Marca cuando camines!",
        "walk_last_time": "Último paseo",
        "walk_reminder_title": "¿Caminaste hoy? 🚶",
        "walk_reminder_1": "¡Caminar mejora el peristaltismo intestinal! 💪",
        "walk_reminder_2": "¡Movimiento = pedos = salud! 💨",
        "walk_reminder_3": "Siéntate menos, camina más — ¡tu intestino lo agradecerá! 🙏",
        "walk_reminder_4": "¿10000 pasos = 100 pedos? ¡Comprobémoslo! 📊",
        "walk_reminder_5": "Una caminata ayuda a la digestión — ¡sal a tomar aire! 🌿",
        "walk_reminder_dismiss": "¡Ya caminé!",
        "walk_reminder_later": "Luego",
        "walk_xp_gain": "¡+8 XP por caminar!",
        "walk_xp_capped": "XP de caminar al máximo hoy (máx 2)",
        # ---- backup_* (8 keys) ----
        "backup_section": "Copia de seguridad",
        "backup_now": "💾 Hacer copia ahora",
        "backup_restore": "🔄 Restaurar desde archivo",
        "backup_auto_hint": "La copia se crea automáticamente cada semana. El archivo se guarda en Descargas — sobrevive a limpiar la caché del navegador.",
        "backup_done": "¡Copia guardada en Descargas!",
        "backup_restored": "¡Datos restaurados desde la copia!",
        "backup_invalid": "Archivo de copia inválido",
        "backup_choose_file": "Elegir archivo de copia (.json)",
        # ---- install_* (3 keys) ----
        "install_button_ios_share": "📤 Abrir Compartir",
        "install_button_ios_hint": "Toca el botón → \"Añadir a pantalla de inicio\" → \"Añadir\"",
        "install_iphone_other_button": "🍎 Abrir en Safari",
        # ---- profile_* (3 keys) ----
        "profile_primary_badge": "Principal",
        "profile_secondary_badge": "Sin XP",
        "profile_secondary_hint": "Los perfiles secundarios solo registran pedos. XP, logros y tienda solo están disponibles en el perfil principal.",
        # ---- levels_* (2 keys) ----
        "levels_grid_title": "Niveles",
        "levels_grid_hint": "El nivel no baja cuando compras en la tienda",
    },
    "pt": {
        # ---- bowel_* (74 keys) ----
        "bowel_tracker": "Banheiro",
        "bowel_went": "Fiz número 2",
        "bowel_went_short": "Fui",
        "bowel_today": "visitas hoje",
        "bowel_history": "Histórico (7 dias)",
        "bowel_no_records": "Nada ainda. Marque quando for!",
        "bowel_last_time": "Última visita",
        "bowel_hours_ago": "h atrás",
        "bowel_time_since": "Tempo desde a última",
        "bowel_warning_title": "Atenção! 🚨",
        "bowel_warning_subtitle": "Já se passaram {h}h desde a última visita. Hora de ir!",
        "bowel_correlation": "Correlação com comida",
        "bowel_avg_after": "Média de horas depois",
        "bowel_times_logged": "vezes registradas",
        "bowel_no_correlation": "Adicione comida e marque visitas para ver padrões",
        "bowel_consistency": "Consistência",
        "bowel_normal": "Normal",
        "bowel_loose": "Mole",
        "bowel_hard": "Dura",
        "bowel_bristol_type": "Tipo",
        "bowel_bristol_scale": "Escala de Bristol",
        "bowel_bristol_1": "Bolinhas duras",
        "bowel_bristol_2": "Salsicha com grumos",
        "bowel_bristol_3": "Salsicha com rachaduras",
        "bowel_bristol_4": "Salsicha lisa",
        "bowel_bristol_5": "Bolinhos macios",
        "bowel_bristol_6": "Pedaços fofos",
        "bowel_bristol_7": "Aquoso",
        "bowel_bristol_1_desc": "Grumos duros, difíceis de passar (constipação)",
        "bowel_bristol_2_desc": "Com grumos, dura (constipação)",
        "bowel_bristol_3_desc": "Superfície rachada (normal)",
        "bowel_bristol_4_desc": "Macia, lisa (ideal)",
        "bowel_bristol_5_desc": "Macia com bordas definidas (pouca fibra)",
        "bowel_bristol_6_desc": "Rasgada, pastosa (diarreia leve)",
        "bowel_bristol_7_desc": "Líquida, sem pedaços sólidos (diarreia)",
        "bowel_symptoms": "Sintomas / notas",
        "bowel_symptoms_placeholder": "Inchaço, dor, náusea...",
        "bowel_symptoms_bloating": "Inchaço",
        "bowel_symptoms_pain": "Dor",
        "bowel_symptoms_nausea": "Náusea",
        "bowel_symptoms_heartburn": "Azia",
        "bowel_symptoms_cramps": "Cólicas",
        "bowel_symptoms_none": "Sem sintomas",
        "bowel_tracking_hint": "💡 Para insights úteis, registre o que você come e quando vai ao banheiro",
        "bowel_warning_1": "Depósito amadurecendo, saque em breve! 💰",
        "bowel_warning_2": "Você não é camelo, não pode acumular! 🐪",
        "bowel_warning_3": "Cuidado, pressão subindo! 💥",
        "bowel_warning_4": "Capacidade de armazenamento excedida! ⚠️",
        "bowel_warning_5": "Seu intestino perguntou: quando? 🤔",
        "bowel_warning_6": "Bomba relógio! 💣",
        "bowel_warning_7": "Fogos de artifício a caminho! 🎆",
        "bowel_warning_8": "Não vá a um encontro! 💔",
        "bowel_warning_9": "Armazenamento cheio, descarregue! 📦",
        "bowel_warning_10": "Não segure — isso faz mal! 🚫",
        "bowel_warning_11": "Hora de entregar a mercadoria! 🏭",
        "bowel_warning_12": "Seu intestino espera sua visita! 🚪",
        "bowel_morning_title": "Você já foi hoje? 🚽",
        "bowel_morning_1": "Uma vez por dia é o normal, sem exceções! 📅",
        "bowel_morning_2": "Cadê os resultados? Entregue a mercadoria! 📦",
        "bowel_morning_3": "Não dá pra acumular, tem que compartilhar! 🤲",
        "bowel_morning_4": "Produção parada — desbloqueie a esteira! ⚙️",
        "bowel_morning_5": "Seu intestino espera sua visita! 🚪",
        "bowel_morning_dismiss": "Já fui!",
        "bowel_morning_later": "Depois",
        "bowel_disable": "Desativar rastreamento",
        "bowel_enable": "Ativar rastreamento",
        "bowel_disabled_hint": "Rastreamento desativado. Ative nas configurações.",
        "bowel_xp_gain": "+5 XP por registrar!",
        "bowel_xp_capped": "XP no limite hoje (máx 3)",
        "bowel_edit": "Editar",
        "bowel_edit_time": "Hora",
        "bowel_edit_date": "Data",
        "bowel_save": "Salvar",
        "bowel_cancel": "Cancelar",
        # ---- digest_* (44 keys) ----
        "digest_section": "Seu resumo",
        "digest_period": "últimos 7 dias",
        "digest_avg_rhythm": "Ritmo médio",
        "digest_avg_rhythm_unit": "visitas/dia",
        "digest_avg_rhythm_desc": "Quantas vezes por dia você vai.",
        "digest_top_type": "Tipo mais comum",
        "digest_top_type_unit": "de todas as visitas",
        "digest_top_type_desc_normal": "Normal — tudo certo!",
        "digest_top_type_desc_constipation": "Mais perto de constipação. Beba mais água.",
        "digest_top_type_desc_diarrhea": "Mais perto de diarreia. Reveja sua dieta.",
        "digest_food_trigger": "Gatilho alimentar",
        "digest_food_trigger_unit": "sintomas após",
        "digest_food_trigger_desc": "Esta comida causa mais sintomas.",
        "digest_best_day": "Melhor dia",
        "digest_best_day_unit": "sem sintomas",
        "digest_best_day_unit_with": "{n} sintomas",
        "digest_best_day_desc": "Seu intestino funcionou melhor neste dia.",
        "digest_progress": "Progresso",
        "digest_progress_unit_one": "dia registrado",
        "digest_progress_unit_few": "dias registrados",
        "digest_progress_unit_many": "dias registrados",
        "digest_progress_desc": "Já dá pra ver padrões.",
        "digest_no_data": "Dados insuficientes. Registre visitas e comida!",
        "digest_insight_title": "Insight do dia",
        "digest_insight_1": "Parece que seu intestino adora um horário fixo.",
        "digest_insight_2": "Comida pesada raramente passa despercebida.",
        "digest_insight_3": "O Tipo 5 liderou de novo.",
        "digest_insight_4": "Menos água — o sistema trabalhou mais duro.",
        "digest_insight_5": "Depois de um jantar tarde, tudo fica mais interessante.",
        "digest_insight_6": "Seu intestino não gosta de surpresas.",
        "digest_insight_7": "Estabilidade é seu melhor padrão.",
        "digest_insight_8": "Laticínios talvez não sejam seus amigos aqui.",
        "digest_insight_9": "Depois de comida gordurosa, o quadro fica mais ruidoso.",
        "digest_insight_10": "Seu corpo manda sinais — e não baixinho.",
        "digest_insight_11": "Você tem seus próprios gatilhos alimentares.",
        "digest_insight_12": "O Tipo 5 aparece mais do que você gostaria.",
        "digest_insight_13": "Quando a rotina quebra, os dados também ficam caóticos.",
        "digest_insight_14": "Seu intestino gosta de comida simples e clara.",
        "digest_insight_15": "Um lanche tarde raramente fica sem resposta.",
        "digest_insight_16": "Em alguns dias tudo funciona mais suave.",
        "digest_insight_17": "Tem um padrão bem vivo aqui.",
        "digest_insight_18": "Comida e sintomas estão mais ligados do que parecem.",
        "digest_insight_19": "Seu intestino parece bem falante.",
        "digest_insight_20": "Não chutamos — já temos pistas.",
        # ---- report_* (34 keys) ----
        "report_section": "Relatório para o médico",
        "report_desc": "Exportar PDF/CSV para gastroenterologista",
        "report_button": "📄 Relatório para o médico",
        "report_csv_button": "📊 Baixar CSV",
        "report_title": "Relatório do diário intestinal",
        "report_subtitle": "para gastroenterologista",
        "report_period": "Período",
        "report_period_7": "7 dias",
        "report_period_30": "30 dias",
        "report_period_90": "90 dias",
        "report_print": "🖨️ Imprimir / Salvar PDF",
        "report_summary": "Resumo",
        "report_patient": "Paciente",
        "report_date_range": "Período de observação",
        "report_days_tracked": "dias registrados",
        "report_avg_farts": "Pum/dia",
        "report_avg_poops": "Evacuações/dia",
        "report_norm": "norma",
        "report_water_avg": "Água (copos/dia)",
        "report_walks_week": "Caminhadas por semana",
        "report_bristol_distribution": "Escala de Bristol (distribuição)",
        "report_food_triggers": "Top gatilhos alimentares",
        "report_food_trigger_farts": "puns após",
        "report_food_trigger_poops": "horas até evacuar",
        "report_30day_chart": "Tendência do período",
        "report_symptoms_log": "Registro de sintomas",
        "report_no_symptoms": "Sem sintomas registrados",
        "report_no_data": "Dados insuficientes para o período selecionado",
        "report_generated": "Relatório gerado",
        "report_signature": "Gerado pelo app Contador de Puns",
        "report_disclaimer": "Apenas informativo. Não substitui consulta médica.",
        "report_farts_chart_label": "puns",
        "report_poops_chart_label": "evacuações",
        "report_track_food_hint": "💡 Dica: registre comida para correlacionar com puns e evacuações",
        # ---- health_tip_* (21 keys) ----
        "health_tip_title": "Dica do dia",
        "health_tip_1": "🚶 Caminhar 15 min após as refeições melhora a digestão e reduz gases.",
        "health_tip_2": "💧 Beba 6-8 copos de água por dia — amolece as fezes e previne constipação.",
        "health_tip_3": "🚽 Ir ao banheiro uma vez por dia é normal. Não segure!",
        "health_tip_4": "🥦 Fibras (verduras, frutas, grãos integrais) são o melhor amigo do intestino.",
        "health_tip_5": "⏰ Um horário regular (manhã após o café) treina seu intestino.",
        "health_tip_6": "🏃 Movimento = peristaltismo. Vida sedentária = constipação.",
        "health_tip_7": "☕ Café da manhã estimula o peristaltismo — mas no máximo 2-3 xícaras.",
        "health_tip_8": "🥛 Laticínios dão gases? Talvez intolerância à lactose.",
        "health_tip_9": "🌙 Não coma 3 horas antes de dormir — puns noturnos e inchaço garantidos.",
        "health_tip_10": "🧘 Estresse afeta o intestino direto. Relaxe — e seu intestino agradece.",
        "health_tip_11": "💩 Normal: 1-2 vezes ao dia, Tipo 4 (salsicha lisa) na escala de Bristol.",
        "health_tip_12": "🫘 Feijão, repolho, brócolis — gases garantidos, mas é saudável!",
        "health_tip_13": "🍞 Pão branco e fast food atrasam a digestão. Escolha integral.",
        "health_tip_14": "🚭 Fumar altera o peristaltismo e a microbiota intestinal.",
        "health_tip_15": "💊 Antibióticos matam a flora boa. Restaure com probióticos.",
        "health_tip_16": "🍎 Maçã com casca — fonte natural de pectina para o intestino.",
        "health_tip_17": "🍌 Bananas ajudam na diarreia leve — repõem potássio.",
        "health_tip_18": "🍵 Chá de hortelã alivia cólicas e inchaço após as refeições.",
        "health_tip_19": "🥗 Uma salada antes do prato principal prepara o estômago e reduz gases.",
        "health_tip_20": "🚶‍♂️ 10000 passos por dia = intestino saudável. Comprovado!",
        # ---- walk_* (18 keys) ----
        "walk_tracker": "Caminhar",
        "walk_went": "Caminhei 🚶",
        "walk_went_short": "Caminhei",
        "walk_today": "caminhadas hoje",
        "walk_history": "Histórico (7 dias)",
        "walk_minutes": "minutos",
        "walk_no_records": "Nada ainda. Marque quando caminhar!",
        "walk_last_time": "Última caminhada",
        "walk_reminder_title": "Você caminhou hoje? 🚶",
        "walk_reminder_1": "Caminhar melhora o peristaltismo intestinal! 💪",
        "walk_reminder_2": "Movimento = puns = saúde! 💨",
        "walk_reminder_3": "Sente menos, caminhe mais — seu intestino agradece! 🙏",
        "walk_reminder_4": "10000 passos = 100 puns? Vamos testar! 📊",
        "walk_reminder_5": "Uma caminhada ajuda a digestão — vá tomar um ar! 🌿",
        "walk_reminder_dismiss": "Já caminhei!",
        "walk_reminder_later": "Depois",
        "walk_xp_gain": "+8 XP por caminhar!",
        "walk_xp_capped": "XP de caminhada no limite hoje (máx 2)",
        # ---- backup_* (8 keys) ----
        "backup_section": "Backup de dados",
        "backup_now": "💾 Fazer backup agora",
        "backup_restore": "🔄 Restaurar de arquivo",
        "backup_auto_hint": "O backup é criado automaticamente toda semana. O arquivo é salvo em Downloads — sobrevive a limpar o cache do navegador.",
        "backup_done": "Backup salvo em Downloads!",
        "backup_restored": "Dados restaurados do backup!",
        "backup_invalid": "Arquivo de backup inválido",
        "backup_choose_file": "Escolher arquivo de backup (.json)",
        # ---- install_* (3 keys) ----
        "install_button_ios_share": "📤 Abrir Compartilhar",
        "install_button_ios_hint": "Toque no botão → \"Adicionar à Tela de Início\" → \"Adicionar\"",
        "install_iphone_other_button": "🍎 Abrir no Safari",
        # ---- profile_* (3 keys) ----
        "profile_primary_badge": "Principal",
        "profile_secondary_badge": "Sem XP",
        "profile_secondary_hint": "Perfis secundários só registram puns. XP, conquistas e loja estão disponíveis apenas no perfil principal.",
        # ---- levels_* (2 keys) ----
        "levels_grid_title": "Níveis",
        "levels_grid_hint": "O nível não diminui quando você compra na loja",
    },
    "de": {
        # ---- bowel_* (74 keys) ----
        "bowel_tracker": "Klo",
        "bowel_went": "Großes Geschäft",
        "bowel_went_short": "War",
        "bowel_today": "Gänge heute",
        "bowel_history": "Verlauf (7 Tage)",
        "bowel_no_records": "Noch nichts. Markiere, wenn du gehst!",
        "bowel_last_time": "Letzter Gang",
        "bowel_hours_ago": "Std her",
        "bowel_time_since": "Zeit seit letztem",
        "bowel_warning_title": "Achtung! 🚨",
        "bowel_warning_subtitle": "Seit {h}Std warst du nicht mehr. Zeit zu gehen!",
        "bowel_correlation": "Korrelation mit Essen",
        "bowel_avg_after": "Ø Stunden danach",
        "bowel_times_logged": "mal erfasst",
        "bowel_no_correlation": "Erfasse Essen und Gänge, um Muster zu sehen",
        "bowel_consistency": "Konsistenz",
        "bowel_normal": "Normal",
        "bowel_loose": "Weich",
        "bowel_hard": "Hart",
        "bowel_bristol_type": "Typ",
        "bowel_bristol_scale": "Bristol-Stuhl-Skala",
        "bowel_bristol_1": "Nüsse",
        "bowel_bristol_2": "Wurst mit Klumpen",
        "bowel_bristol_3": "Wurst mit Rissen",
        "bowel_bristol_4": "Glatte Wurst",
        "bowel_bristol_5": "Weiche Klumpen",
        "bowel_bristol_6": "Flusige Stücke",
        "bowel_bristol_7": "Wässrig",
        "bowel_bristol_1_desc": "Harte Klumpen, schwer auszuscheiden (Verstopfung)",
        "bowel_bristol_2_desc": "Klumpig, hart (Verstopfung)",
        "bowel_bristol_3_desc": "Rissige Oberfläche (normal)",
        "bowel_bristol_4_desc": "Weich, glatt (ideal)",
        "bowel_bristol_5_desc": "Weich mit klaren Kanten (zu wenig Ballaststoffe)",
        "bowel_bristol_6_desc": "Zerfetzt, breiig (leichte Diarrhö)",
        "bowel_bristol_7_desc": "Flüssig, ohne feste Stücke (Diarrhö)",
        "bowel_symptoms": "Symptome / Notizen",
        "bowel_symptoms_placeholder": "Blähungen, Schmerzen, Übelkeit...",
        "bowel_symptoms_bloating": "Blähungen",
        "bowel_symptoms_pain": "Schmerzen",
        "bowel_symptoms_nausea": "Übelkeit",
        "bowel_symptoms_heartburn": "Sodbrennen",
        "bowel_symptoms_cramps": "Krämpfe",
        "bowel_symptoms_none": "Keine Symptome",
        "bowel_tracking_hint": "💡 Für nützliche Insights: Erfasse, was du isst und wann du gehst",
        "bowel_warning_1": "Einlage reift, Auszahlung bald! 💰",
        "bowel_warning_2": "Du bist kein Kamel, horten verboten! 🐪",
        "bowel_warning_3": "Achtung, Druck steigt! 💥",
        "bowel_warning_4": "Lagerkapazität überschritten! ⚠️",
        "bowel_warning_5": "Dein Darm fragt: wann? 🤔",
        "bowel_warning_6": "Zeitbombe! 💣",
        "bowel_warning_7": "Feuerwerk im Anflug! 🎆",
        "bowel_warning_8": "Kein Date heute! 💔",
        "bowel_warning_9": "Lager voll, abladen! 📦",
        "bowel_warning_10": "Nicht zurückhalten — das ist ungesund! 🚫",
        "bowel_warning_11": "Zeit, die Ware auszuliefern! 🏭",
        "bowel_warning_12": "Dein Darm wartet auf deinen Besuch! 🚪",
        "bowel_morning_title": "Warst du schon heute? 🚽",
        "bowel_morning_1": "Einmal am Tag ist normal, keine Ausnahmen! 📅",
        "bowel_morning_2": "Wo sind die Ergebnisse? Ware ausliefern! 📦",
        "bowel_morning_3": "Kannst nicht horten, musst teilen! 🤲",
        "bowel_morning_4": "Produktion gestoppt — Förderband freischalten! ⚙️",
        "bowel_morning_5": "Dein Darm wartet auf deinen Besuch! 🚪",
        "bowel_morning_dismiss": "Schon gewesen!",
        "bowel_morning_later": "Später",
        "bowel_disable": "Tracking deaktivieren",
        "bowel_enable": "Tracking aktivieren",
        "bowel_disabled_hint": "Tracking deaktiviert. In Einstellungen aktivieren.",
        "bowel_xp_gain": "+5 XP fürs Tracken!",
        "bowel_xp_capped": "XP heute voll (max 3)",
        "bowel_edit": "Bearbeiten",
        "bowel_edit_time": "Zeit",
        "bowel_edit_date": "Datum",
        "bowel_save": "Speichern",
        "bowel_cancel": "Abbrechen",
        # ---- digest_* (44 keys) ----
        "digest_section": "Dein Digest",
        "digest_period": "letzte 7 Tage",
        "digest_avg_rhythm": "Ø Rhythmus",
        "digest_avg_rhythm_unit": "Klogänge/Tag",
        "digest_avg_rhythm_desc": "Wie oft du pro Tag gehst.",
        "digest_top_type": "Häufigster Typ",
        "digest_top_type_unit": "aller Gänge",
        "digest_top_type_desc_normal": "Normal — alles bestens!",
        "digest_top_type_desc_constipation": "Eher Verstopfung. Trink mehr Wasser.",
        "digest_top_type_desc_diarrhea": "Eher Diarrhö. Prüf deine Ernährung.",
        "digest_food_trigger": "Essenstrigger",
        "digest_food_trigger_unit": "Symptome danach",
        "digest_food_trigger_desc": "Dieses Essen verursacht mehr Symptome.",
        "digest_best_day": "Bester Tag",
        "digest_best_day_unit": "keine Symptome",
        "digest_best_day_unit_with": "{n} Symptome",
        "digest_best_day_desc": "Dein Darm lief an diesem Tag am besten.",
        "digest_progress": "Fortschritt",
        "digest_progress_unit_one": "Tag erfasst",
        "digest_progress_unit_few": "Tage erfasst",
        "digest_progress_unit_many": "Tage erfasst",
        "digest_progress_desc": "Reicht, um Muster zu erkennen.",
        "digest_no_data": "Zu wenig Daten. Erfasse Gänge und Essen!",
        "digest_insight_title": "Insight des Tages",
        "digest_insight_1": "Dein Darm mag offenbar feste Zeiten.",
        "digest_insight_2": "Schweres Essen bleibt selten unbemerkt.",
        "digest_insight_3": "Typ 5 führt wieder.",
        "digest_insight_4": "Weniger Wasser — das System lief härter.",
        "digest_insight_5": "Nach spätem Abendessen wird alles interessanter.",
        "digest_insight_6": "Dein Darm mag keine Überraschungen.",
        "digest_insight_7": "Stabilität ist dein bestes Muster.",
        "digest_insight_8": "Milchprodukte sind hier vielleicht nicht dein Freund.",
        "digest_insight_9": "Nach fettigem Essen wird das Bild lauter.",
        "digest_insight_10": "Dein Körper sendet Signale — und nicht leise.",
        "digest_insight_11": "Du hast eigene Essens-Trigger.",
        "digest_insight_12": "Typ 5 taucht öfter auf, als du willst.",
        "digest_insight_13": "Wenn die Routine bricht, werden die Daten chaotisch.",
        "digest_insight_14": "Dein Darm mag einfaches, klares Essen.",
        "digest_insight_15": "Ein später Snack bleibt selten unbeantwortet.",
        "digest_insight_16": "An manchen Tagen läuft alles runder.",
        "digest_insight_17": "Hier zeichnet sich ein lebendiges Muster ab.",
        "digest_insight_18": "Essen und Symptome sind enger verknüpft, als es scheint.",
        "digest_insight_19": "Dein Darm ist ziemlich gesprächig.",
        "digest_insight_20": "Wir raten nicht — wir haben schon Hinweise.",
        # ---- report_* (34 keys) ----
        "report_section": "Arztbericht",
        "report_desc": "PDF/CSV-Export für Gastroenterologen",
        "report_button": "📄 Arztbericht",
        "report_csv_button": "📊 CSV herunterladen",
        "report_title": "Tagebuch Magen-Darm-Bericht",
        "report_subtitle": "für Gastroenterologen",
        "report_period": "Zeitraum",
        "report_period_7": "7 Tage",
        "report_period_30": "30 Tage",
        "report_period_90": "90 Tage",
        "report_print": "🖨️ Drucken / PDF speichern",
        "report_summary": "Zusammenfassung",
        "report_patient": "Patient",
        "report_date_range": "Beobachtungszeitraum",
        "report_days_tracked": "Tage erfasst",
        "report_avg_farts": "Fürze/Tag",
        "report_avg_poops": "Stuhlgänge/Tag",
        "report_norm": "Norm",
        "report_water_avg": "Wasser (Gläser/Tag)",
        "report_walks_week": "Spaziergänge pro Woche",
        "report_bristol_distribution": "Bristol-Skala (Verteilung)",
        "report_food_triggers": "Top-Essenstrigger",
        "report_food_trigger_farts": "Fürze danach",
        "report_food_trigger_poops": "Stunden bis Stuhlgang",
        "report_30day_chart": "Trend im Zeitraum",
        "report_symptoms_log": "Symptomprotokoll",
        "report_no_symptoms": "Keine Symptome erfasst",
        "report_no_data": "Zu wenig Daten für den Zeitraum",
        "report_generated": "Bericht erstellt",
        "report_signature": "Erstellt von der Fürz-Zähler-App",
        "report_disclaimer": "Nur informativ. Ersetzt keine ärztliche Beratung.",
        "report_farts_chart_label": "Fürze",
        "report_poops_chart_label": "Stuhlgänge",
        "report_track_food_hint": "💡 Tipp: Erfasse Essen, um es mit Fürzen und Stuhlgängen zu korrelieren",
        # ---- health_tip_* (21 keys) ----
        "health_tip_title": "Tipp des Tages",
        "health_tip_1": "🚶 Ein 15-Minuten-Spaziergang nach dem Essen verbessert die Verdauung und reduziert Gase.",
        "health_tip_2": "💧 Trink 6-8 Gläser Wasser am Tag — weicht den Stuhl auf und verhindert Verstopfung.",
        "health_tip_3": "🚽 Einmal am Tag groß zu gehen ist normal. Nicht zurückhalten!",
        "health_tip_4": "🥦 Ballaststoffe (Gemüse, Obst, Vollkorn) sind deines Darms bester Freund.",
        "health_tip_5": "⏰ Ein fester Kloplan (morgens nach dem Frühstück) trainiert deinen Darm.",
        "health_tip_6": "🏃 Bewegung = Peristaltik. Sitzender Lebensstil = Verstopfung.",
        "health_tip_7": "☕ Morgenkaffee regt die Peristaltik an — aber nicht mehr als 2-3 Tassen.",
        "health_tip_8": "🥛 Milchprodukte geben Gase? Vielleicht Laktoseintoleranz.",
        "health_tip_9": "🌙 Iss 3 Stunden vor dem Schlafen nichts — Nachtfürze und Blähungen garantiert.",
        "health_tip_10": "🧘 Stress beeinflusst den Darm direkt. Entspann dich — dein Darm dankt's.",
        "health_tip_11": "💩 Normal: 1-2 mal am Tag, Typ 4 (glatte Wurst) auf der Bristol-Skala.",
        "health_tip_12": "🫘 Bohnen, Kohl, Brokkoli — Gase garantiert, aber gesund!",
        "health_tip_13": "🍞 Weißbrot und Fast Food verlangsamen die Verdauung. Wähl Vollkorn.",
        "health_tip_14": "🚭 Rauchen stört Peristaltik und Darmmikrobiom.",
        "health_tip_15": "💊 Antibiotika töten die gute Flora. Mit Probiotika wieder aufbauen.",
        "health_tip_16": "🍎 Äpfel mit Schale — natürliche Pektinquelle für den Darm.",
        "health_tip_17": "🍌 Bananen helfen bei leichter Diarrhö — Kalium wird aufgefüllt.",
        "health_tip_18": "🍵 Pfefferminztee löst Krämpfe und Blähungen nach dem Essen.",
        "health_tip_19": "🥗 Ein Salat vor dem Hauptgericht bereitet den Magen vor und reduziert Gase.",
        "health_tip_20": "🚶‍♂️ 10000 Schritte am Tag = gesunder Darm. Bewiesen!",
        # ---- walk_* (18 keys) ----
        "walk_tracker": "Spazieren",
        "walk_went": "Ich spaziert 🚶",
        "walk_went_short": "Spaziert",
        "walk_today": "Gänge heute",
        "walk_history": "Verlauf (7 Tage)",
        "walk_minutes": "Minuten",
        "walk_no_records": "Noch nichts. Markiere, wenn du spazierst!",
        "walk_last_time": "Letzter Spaziergang",
        "walk_reminder_title": "Warst du heute spazieren? 🚶",
        "walk_reminder_1": "Spazieren verbessert die Darmperistaltik! 💪",
        "walk_reminder_2": "Bewegung = Fürze = Gesundheit! 💨",
        "walk_reminder_3": "Weniger sitzen, mehr spazieren — dein Darm dankt! 🙏",
        "walk_reminder_4": "10000 Schritte = 100 Fürze? Testen wir! 📊",
        "walk_reminder_5": "Ein Spaziergang hilft der Verdauung — geh an die Luft! 🌿",
        "walk_reminder_dismiss": "Schon spaziert!",
        "walk_reminder_later": "Später",
        "walk_xp_gain": "+8 XP fürs Spazieren!",
        "walk_xp_capped": "Spaziergang-XP heute voll (max 2)",
        # ---- backup_* (8 keys) ----
        "backup_section": "Datensicherung",
        "backup_now": "💾 Jetzt sichern",
        "backup_restore": "🔄 Aus Datei wiederherstellen",
        "backup_auto_hint": "Sicherung wird wöchentlich automatisch erstellt. Datei landet in Downloads — überlebt das Leeren des Browser-Caches.",
        "backup_done": "Sicherung in Downloads gespeichert!",
        "backup_restored": "Daten aus Sicherung wiederhergestellt!",
        "backup_invalid": "Ungültige Sicherungsdatei",
        "backup_choose_file": "Sicherungsdatei wählen (.json)",
        # ---- install_* (3 keys) ----
        "install_button_ios_share": "📤 Teilen öffnen",
        "install_button_ios_hint": "Tippe auf den Button → \"Zum Home-Bildschirm\" → \"Hinzufügen\"",
        "install_iphone_other_button": "🍎 In Safari öffnen",
        # ---- profile_* (3 keys) ----
        "profile_primary_badge": "Primär",
        "profile_secondary_badge": "Kein XP",
        "profile_secondary_hint": "Sekundärprofile tracken nur Fürze. XP, Erfolge und Shop gibt's nur im primären Profil.",
        # ---- levels_* (2 keys) ----
        "levels_grid_title": "Level",
        "levels_grid_hint": "Level sinkt nicht, wenn du im Shop kaufst",
    },
    "fr": {
        # ---- bowel_* (74 keys) ----
        "bowel_tracker": "Toilettes",
        "bowel_went": "Fait caca",
        "bowel_went_short": "Fait",
        "bowel_today": "visites aujourd'hui",
        "bowel_history": "Historique (7 jours)",
        "bowel_no_records": "Rien pour l'instant. Marque quand tu y vas !",
        "bowel_last_time": "Dernière visite",
        "bowel_hours_ago": "h",
        "bowel_time_since": "Temps écoulé",
        "bowel_warning_title": "Attention ! 🚨",
        "bowel_warning_subtitle": "Ça fait {h}h depuis la dernière visite. Il est temps d'y aller !",
        "bowel_correlation": "Corrélation avec la nourriture",
        "bowel_avg_after": "Moyenne d'heures après",
        "bowel_times_logged": "fois enregistrées",
        "bowel_no_correlation": "Ajoute de la nourriture et marque les visites pour voir des modèles",
        "bowel_consistency": "Consistance",
        "bowel_normal": "Normal",
        "bowel_loose": "Mou",
        "bowel_hard": "Dur",
        "bowel_bristol_type": "Type",
        "bowel_bristol_scale": "Échelle de Bristol",
        "bowel_bristol_1": "Noisettes",
        "bowel_bristol_2": "Saucisse grumeleuse",
        "bowel_bristol_3": "Saucisse craquelée",
        "bowel_bristol_4": "Saucisse lisse",
        "bowel_bristol_5": "Boules molles",
        "bowel_bristol_6": "Morceaux mous",
        "bowel_bristol_7": "Aqueux",
        "bowel_bristol_1_desc": "Grumeaux durs, difficiles à évacuer (constipation)",
        "bowel_bristol_2_desc": "Grumeleuse, dure (constipation)",
        "bowel_bristol_3_desc": "Surface craquelée (normal)",
        "bowel_bristol_4_desc": "Molle, lisse (idéal)",
        "bowel_bristol_5_desc": "Molle aux bords nets (manque de fibres)",
        "bowel_bristol_6_desc": "Déchiquetée, pâteuse (diarrhée légère)",
        "bowel_bristol_7_desc": "Liquide, sans morceaux solides (diarrhée)",
        "bowel_symptoms": "Symptômes / notes",
        "bowel_symptoms_placeholder": "Ballonnements, douleurs, nausées...",
        "bowel_symptoms_bloating": "Ballonnements",
        "bowel_symptoms_pain": "Douleur",
        "bowel_symptoms_nausea": "Nausée",
        "bowel_symptoms_heartburn": "Brûlure d'estomac",
        "bowel_symptoms_cramps": "Crampes",
        "bowel_symptoms_none": "Aucun symptôme",
        "bowel_tracking_hint": "💡 Pour des infos utiles, suis ce que tu manges et quand tu vas aux toilettes",
        "bowel_warning_1": "Le dépôt mûrit, retrait bientôt ! 💰",
        "bowel_warning_2": "Tu n'es pas un chameau, pas de thésaurisation ! 🐪",
        "bowel_warning_3": "Attention, la pression monte ! 💥",
        "bowel_warning_4": "Capacité de stockage dépassée ! ⚠️",
        "bowel_warning_5": "Tes intestins demandent : quand ? 🤔",
        "bowel_warning_6": "Bombe à retardement ! 💣",
        "bowel_warning_7": "Feu d'artifice imminent ! 🎆",
        "bowel_warning_8": "Pas de rendez-vous aujourd'hui ! 💔",
        "bowel_warning_9": "Stockage plein, décharge ! 📦",
        "bowel_warning_10": "Ne te retiens pas — c'est mauvais ! 🚫",
        "bowel_warning_11": "C'est l'heure de livrer la marchandise ! 🏭",
        "bowel_warning_12": "Tes intestins attendent ta visite ! 🚪",
        "bowel_morning_title": "Tu y es déjà allé aujourd'hui ? 🚽",
        "bowel_morning_1": "Une fois par jour, c'est la norme, pas d'exception ! 📅",
        "bowel_morning_2": "Où sont les résultats ? Livre la marchandise ! 📦",
        "bowel_morning_3": "Tu ne peux pas thésauriser, faut partager ! 🤲",
        "bowel_morning_4": "Production stoppée — débloque le tapis ! ⚙️",
        "bowel_morning_5": "Tes intestins attendent ta visite ! 🚪",
        "bowel_morning_dismiss": "Déjà fait !",
        "bowel_morning_later": "Plus tard",
        "bowel_disable": "Désactiver le suivi",
        "bowel_enable": "Activer le suivi",
        "bowel_disabled_hint": "Suivi désactivé. Active-le dans les réglages.",
        "bowel_xp_gain": "+5 XP pour le suivi !",
        "bowel_xp_capped": "XP au max aujourd'hui (max 3)",
        "bowel_edit": "Modifier",
        "bowel_edit_time": "Heure",
        "bowel_edit_date": "Date",
        "bowel_save": "Enregistrer",
        "bowel_cancel": "Annuler",
        # ---- digest_* (44 keys) ----
        "digest_section": "Ton résumé",
        "digest_period": "7 derniers jours",
        "digest_avg_rhythm": "Rythme moyen",
        "digest_avg_rhythm_unit": "visites/jour",
        "digest_avg_rhythm_desc": "Combien de fois par jour tu y vas.",
        "digest_top_type": "Type le plus fréquent",
        "digest_top_type_unit": "de toutes les visites",
        "digest_top_type_desc_normal": "Normal — tout va bien !",
        "digest_top_type_desc_constipation": "Plutôt constipation. Bois plus d'eau.",
        "digest_top_type_desc_diarrhea": "Plutôt diarrhée. Vérifie ton alimentation.",
        "digest_food_trigger": "Déclencheur",
        "digest_food_trigger_unit": "symptômes après",
        "digest_food_trigger_desc": "Cet aliment cause plus de symptômes.",
        "digest_best_day": "Meilleur jour",
        "digest_best_day_unit": "sans symptôme",
        "digest_best_day_unit_with": "{n} symptômes",
        "digest_best_day_desc": "Tes intestins ont tourné au plus lisse ce jour.",
        "digest_progress": "Progression",
        "digest_progress_unit_one": "jour suivi",
        "digest_progress_unit_few": "jours suivis",
        "digest_progress_unit_many": "jours suivis",
        "digest_progress_desc": "Assez pour repérer des modèles.",
        "digest_no_data": "Pas assez de données. Note les visites et l'alimentation !",
        "digest_insight_title": "Insight du jour",
        "digest_insight_1": "On dirait que tes intestins aiment l'emploi du temps.",
        "digest_insight_2": "La nourriture lourde passe rarement inaperçue.",
        "digest_insight_3": "Le Type 5 a repris la tête.",
        "digest_insight_4": "Moins d'eau — le système a plus forcé.",
        "digest_insight_5": "Après un dîner tardif, tout devient plus intéressant.",
        "digest_insight_6": "Tes intestins n'aiment pas les surprises.",
        "digest_insight_7": "La régularité est ton meilleur pattern.",
        "digest_insight_8": "Les produits laitiers ne sont peut-être pas tes amis ici.",
        "digest_insight_9": "Après un repas gras, le tableau devient plus bruyant.",
        "digest_insight_10": "Ton corps envoie des signaux — pas discrètement.",
        "digest_insight_11": "Tu as tes propres déclencheurs alimentaires.",
        "digest_insight_12": "Le Type 5 apparaît plus souvent que tu ne voudrais.",
        "digest_insight_13": "Quand la routine casse, les données deviennent chaotiques aussi.",
        "digest_insight_14": "Tes intestins aiment la nourriture simple et claire.",
        "digest_insight_15": "Un snack tardif reste rarement sans réponse.",
        "digest_insight_16": "Certains jours, tout roule plus doucement.",
        "digest_insight_17": "Il y a un pattern bien vivant ici.",
        "digest_insight_18": "Alimentation et symptômes sont plus liés qu'ils n'y paraissent.",
        "digest_insight_19": "Tes intestins sont assez bavards.",
        "digest_insight_20": "On ne devine pas — on a déjà des pistes.",
        # ---- report_* (34 keys) ----
        "report_section": "Rapport médecin",
        "report_desc": "Export PDF/CSV pour gastroentérologue",
        "report_button": "📄 Rapport médecin",
        "report_csv_button": "📊 Télécharger CSV",
        "report_title": "Rapport du journal intestinal",
        "report_subtitle": "pour gastroentérologue",
        "report_period": "Période",
        "report_period_7": "7 jours",
        "report_period_30": "30 jours",
        "report_period_90": "90 jours",
        "report_print": "🖨️ Imprimer / Enregistrer PDF",
        "report_summary": "Résumé",
        "report_patient": "Patient",
        "report_date_range": "Période d'observation",
        "report_days_tracked": "jours suivis",
        "report_avg_farts": "Pets/jour",
        "report_avg_poops": "Selles/jour",
        "report_norm": "norme",
        "report_water_avg": "Eau (verres/jour)",
        "report_walks_week": "Balades par semaine",
        "report_bristol_distribution": "Échelle de Bristol (répartition)",
        "report_food_triggers": "Top déclencheurs",
        "report_food_trigger_farts": "pets après",
        "report_food_trigger_poops": "heures avant selle",
        "report_30day_chart": "Tendance sur la période",
        "report_symptoms_log": "Journal des symptômes",
        "report_no_symptoms": "Aucun symptôme enregistré",
        "report_no_data": "Pas assez de données pour la période sélectionnée",
        "report_generated": "Rapport généré",
        "report_signature": "Généré par l'app Compteur de Pets",
        "report_disclaimer": "À titre informatif. Ne remplace pas une consultation médicale.",
        "report_farts_chart_label": "pets",
        "report_poops_chart_label": "selles",
        "report_track_food_hint": "💡 Astuce : note ton alimentation pour corréler avec pets et selles",
        # ---- health_tip_* (21 keys) ----
        "health_tip_title": "Conseil du jour",
        "health_tip_1": "🚶 Une marche de 15 min après le repas améliore la digestion et réduit les gaz.",
        "health_tip_2": "💧 Bois 6-8 verres d'eau par jour — ramollit les selles et prévient la constipation.",
        "health_tip_3": "🚽 Aller à la selle une fois par jour, c'est normal. Ne te retiens pas !",
        "health_tip_4": "🥦 Les fibres (légumes, fruits, céréales complètes) sont les meilleures amies de tes intestins.",
        "health_tip_5": "⏰ Un horaire régulier (matin après le petit-déj) entraîne tes intestins.",
        "health_tip_6": "🏃 Mouvement = péristaltisme. Sédentarité = constipation.",
        "health_tip_7": "☕ Le café du matin stimule le péristaltisme — mais pas plus de 2-3 tasses.",
        "health_tip_8": "🥛 Les produits laitiers donnent des gaz ? Peut-être une intolérance au lactose.",
        "health_tip_9": "🌙 Ne mange pas 3 heures avant de dormir — pets nocturnes et ballonnements garantis.",
        "health_tip_10": "🧘 Le stress affecte tes intestins directement. Détends-toi — ils te diront merci.",
        "health_tip_11": "💩 Normal : 1-2 fois par jour, Type 4 (saucisse lisse) sur l'échelle de Bristol.",
        "health_tip_12": "🫘 Haricots, chou, brocoli — gaz garantis, mais c'est sain !",
        "health_tip_13": "🍞 Le pain blanc et la malbouffe ralentissent la digestion. Privilégie le complet.",
        "health_tip_14": "🚭 Fumer perturbe le péristaltisme et le microbiome intestinal.",
        "health_tip_15": "💊 Les antibiotiques tuent la bonne flore. Restaure-la avec des probiotiques.",
        "health_tip_16": "🍎 Pommes avec peau — source naturelle de pectine pour tes intestins.",
        "health_tip_17": "🍌 Les bananes aident en cas de diarrhée légère — le potassium est reconstitué.",
        "health_tip_18": "🍵 La tisane à la menthe soulage crampes et ballonnements après les repas.",
        "health_tip_19": "🥗 Une salade avant le plat principal prépare l'estomac et réduit les gaz.",
        "health_tip_20": "🚶‍♂️ 10000 pas par jour = intestins en bonne santé. Prouvé !",
        # ---- walk_* (18 keys) ----
        "walk_tracker": "Marche",
        "walk_went": "J'ai marché 🚶",
        "walk_went_short": "Marché",
        "walk_today": "balades aujourd'hui",
        "walk_history": "Historique (7 jours)",
        "walk_minutes": "minutes",
        "walk_no_records": "Rien pour l'instant. Marque quand tu marches !",
        "walk_last_time": "Dernière balade",
        "walk_reminder_title": "Tu as marché aujourd'hui ? 🚶",
        "walk_reminder_1": "Marcher améliore le péristaltisme ! 💪",
        "walk_reminder_2": "Mouvement = pets = santé ! 💨",
        "walk_reminder_3": "Moins assis, plus de marche — tes intestins te diront merci ! 🙏",
        "walk_reminder_4": "10000 pas = 100 pets ? On vérifie ! 📊",
        "walk_reminder_5": "Une balade aide la digestion — va prendre l'air ! 🌿",
        "walk_reminder_dismiss": "Déjà marché !",
        "walk_reminder_later": "Plus tard",
        "walk_xp_gain": "+8 XP pour la marche !",
        "walk_xp_capped": "XP de marche au max aujourd'hui (max 2)",
        # ---- backup_* (8 keys) ----
        "backup_section": "Sauvegarde",
        "backup_now": "💾 Sauvegarder maintenant",
        "backup_restore": "🔄 Restaurer depuis un fichier",
        "backup_auto_hint": "Sauvegarde auto chaque semaine. Le fichier va dans Téléchargements — survit au nettoyage du cache du navigateur.",
        "backup_done": "Sauvegarde enregistrée dans Téléchargements !",
        "backup_restored": "Données restaurées depuis la sauvegarde !",
        "backup_invalid": "Fichier de sauvegarde invalide",
        "backup_choose_file": "Choisir un fichier de sauvegarde (.json)",
        # ---- install_* (3 keys) ----
        "install_button_ios_share": "📤 Ouvrir Partage",
        "install_button_ios_hint": "Touche le bouton → \"Sur l'écran d'accueil\" → \"Ajouter\"",
        "install_iphone_other_button": "🍎 Ouvrir dans Safari",
        # ---- profile_* (3 keys) ----
        "profile_primary_badge": "Principal",
        "profile_secondary_badge": "Sans XP",
        "profile_secondary_hint": "Les profils secondaires ne suivent que les pets. XP, succès et boutique ne sont disponibles que sur le profil principal.",
        # ---- levels_* (2 keys) ----
        "levels_grid_title": "Niveaux",
        "levels_grid_hint": "Le niveau ne baisse pas quand tu achètes à la boutique",
    },
    "hi": {
        # ---- bowel_* (74 keys) ----
        "bowel_tracker": "शौचालय",
        "bowel_went": "पखाना हो गया",
        "bowel_went_short": "हो गया",
        "bowel_today": "आज की विज़िट",
        "bowel_history": "इतिहास (7 दिन)",
        "bowel_no_records": "अभी कुछ नहीं। जाने पर मार्क करें!",
        "bowel_last_time": "आखिरी विज़िट",
        "bowel_hours_ago": "घंटे पहले",
        "bowel_time_since": "पिछली बार से समय",
        "bowel_warning_title": "ध्यान दें! 🚨",
        "bowel_warning_subtitle": "पिछली विज़िट को {h}घंटे हो गए। अब जाने का समय!",
        "bowel_correlation": "खाने से संबंध",
        "bowel_avg_after": "औसतन घंटे बाद",
        "bowel_times_logged": "बार दर्ज",
        "bowel_no_correlation": "खाना और विज़िट जोड़ें — पैटर्न दिखेंगे",
        "bowel_consistency": "कंसिस्टेंसी",
        "bowel_normal": "सामान्य",
        "bowel_loose": "ढीला",
        "bowel_hard": "कड़क",
        "bowel_bristol_type": "प्रकार",
        "bowel_bristol_scale": "ब्रिस्टल स्टूल स्केल",
        "bowel_bristol_1": "कड़े दाने",
        "bowel_bristol_2": "गांठदार सॉसेज",
        "bowel_bristol_3": "दरारदार सॉसेज",
        "bowel_bristol_4": "चिकनी सॉसेज",
        "bowel_bristol_5": "मुलायम गोलियां",
        "bowel_bristol_6": "फुले हुए टुकड़े",
        "bowel_bristol_7": "पानी जैसा",
        "bowel_bristol_1_desc": "कड़े दाने, निकालना मुश्किल (कब्ज़)",
        "bowel_bristol_2_desc": "गांठदार, कड़क (कब्ज़)",
        "bowel_bristol_3_desc": "सतह पर दरारें (सामान्य)",
        "bowel_bristol_4_desc": "मुलायम, चिकना (आदर्श)",
        "bowel_bristol_5_desc": "मुलायम, साफ़ किनारे (फाइबर कम)",
        "bowel_bristol_6_desc": "फटा हुआ, नरम (हल्की डायरिया)",
        "bowel_bristol_7_desc": "तरल, कोई ठोस टुकड़ा नहीं (डायरिया)",
        "bowel_symptoms": "लक्षण / नोट्स",
        "bowel_symptoms_placeholder": "सूजन, दर्द, जी मिचलाना...",
        "bowel_symptoms_bloating": "सूजन",
        "bowel_symptoms_pain": "दर्द",
        "bowel_symptoms_nausea": "जी मिचलाना",
        "bowel_symptoms_heartburn": "सीने में जलन",
        "bowel_symptoms_cramps": "ऐंठन",
        "bowel_symptoms_none": "कोई लक्षण नहीं",
        "bowel_tracking_hint": "💡 उपयोगी जानकारी के लिए ट्रैक करें कि आप क्या खाते हैं और कब जाते हैं",
        "bowel_warning_1": "जमा पक रहा है, जल्द निकासी! 💰",
        "bowel_warning_2": "आप ऊंट नहीं हैं, जमा नहीं कर सकते! 🐪",
        "bowel_warning_3": "सावधान, दबाव बढ़ रहा है! 💥",
        "bowel_warning_4": "स्टोरेज क्षमता पार हो गई! ⚠️",
        "bowel_warning_5": "आपकी आंत पूछ रही है: कब? 🤔",
        "bowel_warning_6": "टाइम बम! 💣",
        "bowel_warning_7": "आतिशबाज़ी आ रही है! 🎆",
        "bowel_warning_8": "डेट पर मत जाइए! 💔",
        "bowel_warning_9": "स्टोरेज भर गया, खाली करें! 📦",
        "bowel_warning_10": "रोक कर मत रखिए — ये नुक़सानदेह है! 🚫",
        "bowel_warning_11": "उत्पाद सौंपने का समय! 🏭",
        "bowel_warning_12": "आपकी आंत आपकी विज़िट का इंतज़ार कर रही है! 🚪",
        "bowel_morning_title": "क्या आप आज गए? 🚽",
        "bowel_morning_1": "दिन में एक बार नॉर्म है, कोई छूट नहीं! 📅",
        "bowel_morning_2": "नतीजे कहाँ हैं? उत्पाद सौंपिए! 📦",
        "bowel_morning_3": "जमा नहीं कर सकते, बांटना होगा! 🤲",
        "bowel_morning_4": "उत्पादन रुका — कन्वेयर चालू कीजिए! ⚙️",
        "bowel_morning_5": "आपकी आंत आपकी विज़िट का इंतज़ार कर रही है! 🚪",
        "bowel_morning_dismiss": "हो गया!",
        "bowel_morning_later": "बाद में",
        "bowel_disable": "ट्रैकिंग बंद करें",
        "bowel_enable": "ट्रैकिंग शुरू करें",
        "bowel_disabled_hint": "ट्रैकिंग बंद है. सेटिंग्स में चालू करें.",
        "bowel_xp_gain": "ट्रैकिंग के लिए +5 XP!",
        "bowel_xp_capped": "आज का XP मिल चुका (अधिकतम 3)",
        "bowel_edit": "एडिट",
        "bowel_edit_time": "समय",
        "bowel_edit_date": "तारीख़",
        "bowel_save": "सेव",
        "bowel_cancel": "रद्द",
        # ---- digest_* (44 keys) ----
        "digest_section": "आपका सारांश",
        "digest_period": "पिछले 7 दिन",
        "digest_avg_rhythm": "औसत लय",
        "digest_avg_rhythm_unit": "विज़िट/दिन",
        "digest_avg_rhythm_desc": "आप दिन में कितनी बार जाते हैं.",
        "digest_top_type": "सबसे आम प्रकार",
        "digest_top_type_unit": "कुल विज़िट में से",
        "digest_top_type_desc_normal": "सामान्य — सब ठीक है!",
        "digest_top_type_desc_constipation": "कब्ज़ के पास. ज़्यादा पानी पिएं.",
        "digest_top_type_desc_diarrhea": "डायरिया के पास. अपना खाना जांचें.",
        "digest_food_trigger": "खाना ट्रिगर",
        "digest_food_trigger_unit": "बाद में लक्षण",
        "digest_food_trigger_desc": "यह खाना ज़्यादा लक्षण देता है.",
        "digest_best_day": "सर्वश्रेष्ठ दिन",
        "digest_best_day_unit": "लक्षण नहीं",
        "digest_best_day_unit_with": "{n} लक्षण",
        "digest_best_day_desc": "इस दिन आपकी आंत सबसे स्मूथ चली.",
        "digest_progress": "प्रगति",
        "digest_progress_unit_one": "दिन ट्रैक किया",
        "digest_progress_unit_few": "दिन ट्रैक किए",
        "digest_progress_unit_many": "दिन ट्रैक किए",
        "digest_progress_desc": "पैटर्न देखने के लिए काफ़ी है.",
        "digest_no_data": "पर्याप्त डेटा नहीं. विज़िट और खाना दर्ज करें!",
        "digest_insight_title": "आज की अंतर्दृष्टि",
        "digest_insight_1": "लगता है आपकी आंत को शेड्यूल पसंद है.",
        "digest_insight_2": "भारी खाना अक्सर नज़रअंदाज़ नहीं होता.",
        "digest_insight_3": "टाइप 5 फिर आगे रहा.",
        "digest_insight_4": "पानी कम — सिस्टम ज़्यादा मेहनत कर रहा था.",
        "digest_insight_5": "देर से डिनर के बाद सब ज़्यादा दिलचस्प हो जाता है.",
        "digest_insight_6": "आपकी आंत सरप्राइज़ पसंद नहीं करती.",
        "digest_insight_7": "स्थिरता ही आपका सबसे अच्छा पैटर्न है.",
        "digest_insight_8": "शायद डेयरी आपकी दोस्त नहीं यहाँ.",
        "digest_insight_9": "तले-भुने खाने के बाद तस्वीर ज़्यादा शोर भरी होती है.",
        "digest_insight_10": "आपका शरीर संकेत भेज रहा है — चुपके से नहीं.",
        "digest_insight_11": "आपके अपने खाना ट्रिगर हैं.",
        "digest_insight_12": "टाइप 5 ज़्यादा बार आता है जितना आप चाहें.",
        "digest_insight_13": "रूटीन टूटने पर डेटा भी अस्त-व्यस्त हो जाता है.",
        "digest_insight_14": "आपकी आंत साधारण, साफ़ खाना पसंद करती है.",
        "digest_insight_15": "देर की नाश्ता अक्सर बिना जवाब नहीं रहता.",
        "digest_insight_16": "कुछ दिन सब कुछ ज़्यादा स्मूथ चलता है.",
        "digest_insight_17": "यहाँ एक जीवंत पैटर्न झलकता है.",
        "digest_insight_18": "खाना और लक्षण जुड़े हैं, जितना लगता है उससे ज़्यादा.",
        "digest_insight_19": "आपकी आंत काफ़ी बातूनी लगती है.",
        "digest_insight_20": "हम अंदाज़े नहीं लगाते — हमें संकेत मिल चुके हैं.",
        # ---- report_* (34 keys) ----
        "report_section": "डॉक्टर रिपोर्ट",
        "report_desc": "गैस्ट्रोएंटरोलॉजिस्ट के लिए PDF/CSV एक्सपोर्ट",
        "report_button": "📄 डॉक्टर रिपोर्ट",
        "report_csv_button": "📊 CSV डाउनलोड",
        "report_title": "जीआई ट्रैक्ट डायरी रिपोर्ट",
        "report_subtitle": "गैस्ट्रोएंटरोलॉजिस्ट के लिए",
        "report_period": "अवधि",
        "report_period_7": "7 दिन",
        "report_period_30": "30 दिन",
        "report_period_90": "90 दिन",
        "report_print": "🖨️ प्रिंट / PDF सेव करें",
        "report_summary": "सारांश",
        "report_patient": "मरीज़",
        "report_date_range": "निरीक्षण अवधि",
        "report_days_tracked": "दिन ट्रैक किए",
        "report_avg_farts": "पाद/दिन",
        "report_avg_poops": "मल विसर्जन/दिन",
        "report_norm": "नॉर्म",
        "report_water_avg": "पानी (गिलास/दिन)",
        "report_walks_week": "हफ़्ते में सैर",
        "report_bristol_distribution": "ब्रिस्टल स्केल (वितरण)",
        "report_food_triggers": "टॉप खाना ट्रिगर",
        "report_food_trigger_farts": "बाद में पाद",
        "report_food_trigger_poops": "मल तक घंटे",
        "report_30day_chart": "अवधि में रुझान",
        "report_symptoms_log": "लक्षण लॉग",
        "report_no_symptoms": "कोई लक्षण लॉग नहीं",
        "report_no_data": "चुनी गई अवधि के लिए पर्याप्त डेटा नहीं",
        "report_generated": "रिपोर्ट तैयार",
        "report_signature": "पाद काउंटर ऐप द्वारा तैयार",
        "report_disclaimer": "केवल जानकारी के लिए. डॉक्टरी सलाह का विकल्प नहीं.",
        "report_farts_chart_label": "पाद",
        "report_poops_chart_label": "मल विसर्जन",
        "report_track_food_hint": "💡 सुझाव: पाद और मल के साथ संबंध देखने के लिए खाना लॉग करें",
        # ---- health_tip_* (21 keys) ----
        "health_tip_title": "आज की सलाह",
        "health_tip_1": "🚶 खाने के बाद 15 मिनट सैर पाचन बेहतर करती है और गैस कम करती है.",
        "health_tip_2": "💧 रोज़ 6-8 गिलास पानी पिएं — मल को नरम रखता है और कब्ज़ रोकता है.",
        "health_tip_3": "🚽 दिन में एक बार जाना सामान्य है. रोक कर मत रखिए!",
        "health_tip_4": "🥦 फाइबर (सब्ज़ियां, फल, साबुत अनाज) आपकी आंत का सबसे अच्छा दोस्त है.",
        "health_tip_5": "⏰ नियत समय (नाश्ते के बाद सुबह) आपकी आंत को ट्रेन करता है.",
        "health_tip_6": "🏃 मूवमेंट = पेरिस्टल्सिस. बैठकर काम = कब्ज़.",
        "health_tip_7": "☕ सुबह कॉफ़ी पेरिस्टल्सिस को उत्तेजित करती है — पर 2-3 कप से ज़्यादा नहीं.",
        "health_tip_8": "🥛 डेयरी से गैस? शायद लैक्टोज़ असहिष्णुता हो.",
        "health_tip_9": "🌙 सोने से 3 घंटे पहले खाना मत खाइए — रात के पाद और सूजन पक्के.",
        "health_tip_10": "🧘 तनाव सीधे आंत को प्रभावित करता है. आराम कीजिए — आंत शुक्रिया कहेगी.",
        "health_tip_11": "💩 सामान्य: दिन में 1-2 बार, ब्रिस्टल पैमाने पर टाइप 4 (चिकनी सॉसेज).",
        "health_tip_12": "🫘 बीन्स, पत्तागोभी, ब्रोकली — गैस पक्की, पर ये सेहतमंद है!",
        "health_tip_13": "🍞 सफ़ेद ब्रेड और फास्ट फूड पाचन धीमा करते हैं. साबुत अनाज चुनें.",
        "health_tip_14": "🚭 धूम्रपान पेरिस्टल्सिस और आंत माइक्रोबायोम बिगाड़ता है.",
        "health_tip_15": "💊 एंटीबायोटिक्स अच्छी फ्लोरा मारते हैं. प्रोबायोटिक्स से फिर बहाल करें.",
        "health_tip_16": "🍎 छिलके सहित सेब — आपकी आंत के लिए प्राकृतिक पेक्टिन स्रोत.",
        "health_tip_17": "🍌 केला हल्की डायरिया में मदद करता है — पोटैशियम भर जाता है.",
        "health_tip_18": "🍵 पुदीने की चाय ऐंठन और सूजन दूर करती है खाने के बाद.",
        "health_tip_19": "🥗 मुख्य व्यंजन से पहले सलाद पेट तैयार करती है और गैस कम करती है.",
        "health_tip_20": "🚶‍♂️ रोज़ 10000 क़दम = स्वस्थ आंत. सिद्ध!",
        # ---- walk_* (18 keys) ----
        "walk_tracker": "सैर",
        "walk_went": "मैं टहल आया 🚶",
        "walk_went_short": "टहला",
        "walk_today": "आज की सैर",
        "walk_history": "इतिहास (7 दिन)",
        "walk_minutes": "मिनट",
        "walk_no_records": "अभी कुछ नहीं. टहलने पर मार्क करें!",
        "walk_last_time": "आखिरी सैर",
        "walk_reminder_title": "क्या आपने आज सैर की? 🚶",
        "walk_reminder_1": "टहलने से आंत का पेरिस्टल्सिस सुधरता है! 💪",
        "walk_reminder_2": "मूवमेंट = पाद = सेहत! 💨",
        "walk_reminder_3": "कम बैठें, ज़्यादा टहलें — आंत शुक्रिया कहेगी! 🙏",
        "walk_reminder_4": "10000 क़दम = 100 पाद? चेक करते हैं! 📊",
        "walk_reminder_5": "सैर पाचन में मदद करती है — हवा लेने जाइए! 🌿",
        "walk_reminder_dismiss": "टहल आया!",
        "walk_reminder_later": "बाद में",
        "walk_xp_gain": "सैर के लिए +8 XP!",
        "walk_xp_capped": "आज का सैर XP मिल चुका (अधिकतम 2)",
        # ---- backup_* (8 keys) ----
        "backup_section": "डेटा बैकअप",
        "backup_now": "💾 अभी बैकअप लें",
        "backup_restore": "🔄 फ़ाइल से पुनर्स्थापित करें",
        "backup_auto_hint": "हर हफ़्ते अपने-आप बैकअप बनता है. फ़ाइल डाउनलोड्स में सेव होती है — ब्राउज़र कैश मिटाने पर भी बनी रहती है.",
        "backup_done": "बैकअप डाउनलोड्स में सेव हुआ!",
        "backup_restored": "बैकअप से डेटा पुनर्स्थापित!",
        "backup_invalid": "अमान्य बैकअप फ़ाइल",
        "backup_choose_file": "बैकअप फ़ाइल चुनें (.json)",
        # ---- install_* (3 keys) ----
        "install_button_ios_share": "📤 शेयर खोलें",
        "install_button_ios_hint": "बटन दबाएं → \"होम स्क्रीन पर जोड़ें\" → \"जोड़ें\"",
        "install_iphone_other_button": "🍎 Safari में खोलें",
        # ---- profile_* (3 keys) ----
        "profile_primary_badge": "मुख्य",
        "profile_secondary_badge": "XP नहीं",
        "profile_secondary_hint": "द्वितीयक प्रोफ़ाइल सिर्फ़ पाद ट्रैक करती हैं. XP, उपलब्धियां और शॉप सिर्फ़ मुख्य प्रोफ़ाइल में उपलब्ध हैं.",
        # ---- levels_* (2 keys) ----
        "levels_grid_title": "स्तर",
        "levels_grid_hint": "शॉप से ख़रीदने पर स्तर नहीं घटता",
    },
}


def verify_counts():
    """Verify each language has exactly 207 keys."""
    expected = 207
    for lang, d in TRANSLATIONS.items():
        n = len(d)
        assert n == expected, f"{lang}: expected {expected}, got {n}"
        print(f"  {lang}: {n} keys OK")
    # Also verify all 5 langs have the same key set
    base_keys = set(TRANSLATIONS["es"].keys())
    for lang, d in TRANSLATIONS.items():
        if set(d.keys()) != base_keys:
            missing = base_keys - set(d.keys())
            extra = set(d.keys()) - base_keys
            raise AssertionError(f"{lang}: missing {missing}, extra {extra}")
    print("  All 5 languages share the same key set ✓")


def merge_into_locale(lang: str, new_translations: dict) -> int:
    """Merge new translations into existing locale JSON, sorted alphabetically.

    Returns the final key count after merge.
    """
    path = LOCALES_DIR / f"{lang}.json"
    with path.open("r", encoding="utf-8") as f:
        existing = json.load(f)

    before = len(existing)
    # Check for collisions
    collisions = set(existing.keys()) & set(new_translations.keys())
    if collisions:
        raise AssertionError(f"{lang}: {len(collisions)} collisions: {list(collisions)[:5]}...")

    existing.update(new_translations)
    after = len(existing)
    assert after == before + 207, f"{lang}: expected {before + 207}, got {after}"

    # Sort alphabetically by key and write back with 2-space indent + ensure_ascii=False
    sorted_dict = dict(sorted(existing.items(), key=lambda kv: kv[0]))
    with path.open("w", encoding="utf-8") as f:
        json.dump(sorted_dict, f, ensure_ascii=False, indent=2)
        f.write("\n")  # trailing newline, matching the file convention

    return after


def main():
    print("== Verifying translation counts ==")
    verify_counts()

    print("\n== Merging translations into locale files ==")
    for lang in ["es", "pt", "de", "fr", "hi"]:
        before = 637
        after = merge_into_locale(lang, TRANSLATIONS[lang])
        print(f"  {lang}.json: {before} -> {after} keys (added {after - before})")

    print("\n== Validating JSON parse + final counts ==")
    for lang in ["es", "pt", "de", "fr", "hi"]:
        path = LOCALES_DIR / f"{lang}.json"
        with path.open("r", encoding="utf-8") as f:
            data = json.load(f)
        n = len(data)
        marker = "✓" if n == 844 else "✗"
        print(f"  {marker} {lang}.json: {n} keys (expected 844)")

    print("\nDone.")


if __name__ == "__main__":
    main()
